name: wiber_mobile
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: ^5.4.2+1
  flutter_easyloading: ^3.0.5
  flutter_mobx: ^2.2.0+2
  dropdown_button2: ^2.1.4
  modal_bottom_sheet: ^2.1.2
  get_it: ^7.6.0
  injectable: ^2.1.2
  intl: ^0.18.1
  flutter_svg: ^2.0.5
  mobx: ^2.3.2
  auto_route: ^6.4.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  injectable_generator: ^2.1.6
  json_annotation: ^4.8.1
  mobx_codegen: ^2.3.0
  flutter_screenutil: ^5.7.0
  provider: ^6.1.2
  auto_size_text: ^3.0.0
  shared_preferences: ^2.2.2
  worker_manager: ^5.0.3
  auto_route_generator: ^6.2.0
  font_awesome_flutter: ^10.4.0
  easy_mask: ^2.0.1
  secure_storage_helper: ^0.1.1
  fluttertoast: ^8.2.4
  card_swiper: ^3.0.1
  flutter_keyboard_visibility: ^6.0.0
  image_picker: ^1.0.4
  image_cropper: ^4.0.1
  indexed: ^0.0.8
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900